apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-be
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: offer-be
  template:
    metadata:
      labels:
        app: offer-be
    spec:
      containers:
      - image: goharrm/offer-dev
        name: offer-be
        ports:
        - containerPort: 7070


