apiVersion: v1
kind: Service
metadata:
  name: offer-be
spec:
  type: NodePort
  ports:
  - name: http
    port: 7070
    targetPort: 7070
    protocol: TCP
    nodePort: 32667
  selector:
    app: offer-be
  externalTrafficPolicy: Cluster
  sessionAffinity: None