apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: ghcr.io/sihyun0526/seminar2:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development


