name: docker build example

# on:
#   schedule:
#     - cron: "*/7 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t test_image ./
